{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/subscribingstate\/connectionerror(status:reason:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/SubscribingState\/connectionError(status:reason:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Connection Error is received when we fail to connect to the millicast service, for example when a network error"},{"type":"text","text":" "},{"type":"text","text":"occurs or when the stream is not being published to in a non-secure view stream."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"SubscribingState.connectionError(status:reason:)","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:12MillicastSDK16SubscribingStateO15connectionErroryACs5Int32V_SStcACmF","modules":[{"name":"MillicastSDK"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/SubscribingState"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/SubscribingState":{"role":"symbol","title":"SubscribingState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SubscribingState"}],"abstract":[{"type":"text","text":"This enum describes the subscriberâ€™s state changes"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/SubscribingState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SubscribingState"}],"url":"\/documentation\/millicastsdk\/subscribingstate"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/SubscribingState/connectionError(status:reason:)":{"role":"symbol","title":"SubscribingState.connectionError(status:reason:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Connection Error is received when we fail to connect to the millicast service, for example when a network error"},{"type":"text","text":" "},{"type":"text","text":"occurs or when the stream is not being published to in a non-secure view stream."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/SubscribingState\/connectionError(status:reason:)","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/subscribingstate\/connectionerror(status:reason:)"}}}