{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"status","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The HTTP error code."}]}]},{"name":"reason","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Error message."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/publishingstate\/connectionerror(status:reason:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/PublishingState\/connectionError(status:reason:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Connection Error is received when we fail to connect to the millicast service, for example when a network error"},{"type":"text","text":" "},{"type":"text","text":"occurs"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"PublishingState.connectionError(status:reason:)","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:12MillicastSDK15PublishingStateO15connectionErroryACs5Int32V_SStcACmF","modules":[{"name":"MillicastSDK"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/PublishingState"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/PublishingState":{"role":"symbol","title":"PublishingState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PublishingState"}],"abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/PublishingState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PublishingState"}],"url":"\/documentation\/millicastsdk\/publishingstate"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/PublishingState/connectionError(status:reason:)":{"role":"symbol","title":"PublishingState.connectionError(status:reason:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Connection Error is received when we fail to connect to the millicast service, for example when a network error"},{"type":"text","text":" "},{"type":"text","text":"occurs"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/PublishingState\/connectionError(status:reason:)","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/publishingstate\/connectionerror(status:reason:)"}}}